# pragma warning disable

namespace FlightTicketBookingApp.Control_Data
{
    public static class LocationGenerate
    {
        public struct Location (string country, string city, string airport)
        {
            public string Country = country;
            public string City = city;
            public string Airport = airport;
        }

        public static List<Location> locations = new List<Location>
        {
            new Location("", "", ""),
            new Location("Almanya", "Berlin", "Berlin Brandenburg Havalimanı (BER)"),
            new Location("Almanya", "Bremen", "Bremen Havalimanı (BRE)"),
            new Location("Almanya", "Düsseldorf", "Düsseldorf Rhein Ruhr Uluslararası Havalimanı (DUS)"),
            new Location("Almanya", "Frankfurt", "Frankfurt Havalimanı (FRA)"),
            new Location("Almanya", "Friedrichshafen", "Friedrichshafen Havalimanı (FDH)"),
            new Location("Almanya", "Hamburg", "Hamburg Fuhlsbüttel Havalimanı (HAM)"),
            new Location("Almanya", "Hannover", "Hannover Havalimanı (HAJ)"),
            new Location("Almanya", "Karlsruhe", "Karlsruhe/Baden-Baden Havalimanı (FKB)"),
            new Location("Almanya", "Köln", "Köln Bonn Havalimanı (CGN)"),
            new Location("Almanya", "Leipzig", "Leipzig/Halle Havalimanı (LEJ)"),
            new Location("Almanya", "Münih", "Münih Franz Josef Strauss Havalimanı (MUC)"),
            new Location("Almanya", "Nürnberg", "Nürnberg Havalimanı (NUE)"),
            new Location("Almanya", "Stuttgart", "Stuttgart Havalimanı (STR)"),
            new Location("ABD", "Akron/Canton", "Akron Fulton Uluslararası Havalimanı (CAK)"),
            new Location("ABD", "Albany", "Albany Uluslararası Havalimanı (ALB)"),
            new Location("ABD", "Albuquerque", "Uluslararası Sunport Havalimanı (ABQ)"),
            new Location("ABD", "Alexandria", "Alexandria Uluslararası Havalimanı (AEX)"),
            new Location("ABD", "Allentown", "Lehigh Valley Uluslararası Havalimanı (ABE)"),
            new Location("ABD", "Amarillo", "Rick Husband Uluslararası Havalimanı (AMA)"),
            new Location("ABD", "Anchorage", "Ted Stevens Uluslararası Havalimanı (ANC)"),
            new Location("ABD", "Appleton", "Outagamie County Bölgesel Havalimanı (ATW)"),
            new Location("ABD", "Arcata-Eureka", "Arcata Havalimanı (ACV)"),
            new Location("ABD", "Asheville/Hendersonville", "Asheville Bölgesel Havalimanı (AVL)"),
            new Location("ABD", "Aspen", "Pitkin County Havalimanı (ASE)"),
            new Location("ABD", "Atlanta", "Atlanta Hartsfield-Jackson Havalimanı (ATL)"),
            new Location("ABD", "Austin", "Austin-Bergstrom Uluslararası Havalimanı (AUS)"),
            new Location("ABD", "Bakersfield", "Meadows Field Havalimanı (BFL)"),
            new Location("ABD", "Baton Rouge", "Metropolitan-Ryan Havalimanı (BTR)"),
            new Location("ABD", "Beaumont-Port Arthur", "Jack Brooks Bölgesel Havalimanı (BPT)"),
            new Location("ABD", "Bellingham", "Bellingham Havalimanı (BLI)"),
            new Location("ABD", "Billings", "Logan Uluslararası Havalimanı (BIL)"),
            new Location("ABD", "Binghamton", "Greater Binghamton Havalimanı (BGM)"),
            new Location("ABD", "Birmingham", "Shuttlesworth Uluslararası Havalimanı (BHM)"),
            new Location("ABD", "Bismarck", "Bismarck Bölgesel Havalimanı (BIS)"),
            new Location("ABD", "Boise", "Boise (Gowen) Havalimanı (BOI)"),
            new Location("ABD", "Boston", "Boston Logan Uluslararası Havalimanı (BOS)"),
            new Location("ABD", "Bozeman", "Yellowstone Uluslararası Havalimanı (BZN)"),
            new Location("ABD", "Brownsville", "South Padre Island Uluslararası Havalimanı (BRO)"),
            new Location("ABD", "Buffalo", "Buffalo Niagara Uluslararası Havalimanı (BUF)"),
            new Location("ABD", "Burbank", "Bob Hope Havalimanı (BUR)"),
            new Location("ABD", "Burlington", "Burlington Havalimanı (BTV)"),
            new Location("ABD", "Casper", "Natrona County Uluslararası Havalimanı (CPR)"),
            new Location("ABD", "Cedar Rapids", "The Eastern Iowa Havalimanı (CID)"),
            new Location("ABD", "Charleston", "Charleston Havalimanı (CHS)"),
            new Location("ABD", "Charleston", "Yeager Havalimanı (CRW)"),
            new Location("ABD", "Charlotte", "Charlotte Douglas Uluslararası Havalimanı (CLT)"),
            new Location("ABD", "Charlottesville", "Albemarle Havalimanı (CHO)"),
            new Location("ABD", "Chico", "Chico Bölgesel Havalimanı (CIC)"),
            new Location("ABD", "Cincinnati", "Cincinnati Northern Kentucky Uluslararası Havalimanı (CVG)"),
            new Location("ABD", "Cleveland", "Cleveland Hopkins Uluslararası Havalimanı (CLE)"),
            new Location("ABD", "Cody", "Yellowstone Bölgesel Havalimanı (COD)"),
            new Location("ABD", "College Station", "Easterwood Havalimanı (CLL)"),
            new Location("ABD", "Colorado Springs", "Colorado Springs Bölgesel Havalimanı (COS)"),
            new Location("ABD", "Columbia", "Columbia Metropolitan Havalimanı (CAE)"),
            new Location("ABD", "Columbus", "Port Columbus Uluslararası Havalimanı (CMH)"),
            new Location("ABD", "Corpus Christi", "Corpus Christi Uluslararası Havalimanı (CRP)"),
            new Location("ABD", "Crescent City", "Del Norte County Bölgesel Havalimanı (CEC)"),
            new Location("ABD", "Dallas", "Dallas Fort Worth Uluslararası Havalimanı (DFW)"),
            new Location("ABD", "Dallas-Fort Worth", "Love Field Havalimanı (DAL)"),
            new Location("ABD", "Dayton", "Dayton Uluslararası Havalimanı (DAY)"),
            new Location("ABD", "Daytona Beach", "Daytona Beach Uluslararası Havalimanı (DAB)"),
            new Location("ABD", "Del Rio", "Del Rio Uluslararası Havalimanı (DRT)"),
            new Location("ABD", "Denver", "Denver Uluslararası Havalimanı (DEN)"),
            new Location("ABD", "Des Moines", "Des Moines Uluslararası Havalimanı (DSM)"),
            new Location("ABD", "Destin/Fort Walton Beach", "Destin-Fort Walton Beach Havalimanı (VPS)"),
            new Location("ABD", "Detroit", "Detroit Wayne County Havalimanı (DTW)"),
            new Location("ABD", "Durango", "La Plata County Havalimanı (DRO)"),
            new Location("ABD", "Eagle", "Eagle County Bölgesel Havalimanı (EGE)"),
            new Location("ABD", "Eau Claire", "Chippewa Valley Bölgesel Havalimanı (EAU)"),
            new Location("ABD", "El Paso", "El Paso Uluslararası Havalimanı (ELP)"),
            new Location("ABD", "Erie", "Erie Uluslararası Havalimanı (ERI)"),
            new Location("ABD", "Eugene", "Mahlon Sweet Havalimanı (EUG)"),
            new Location("ABD", "Evansville", "Evansville Regional Havalimanı (EVV)"),
            new Location("ABD", "Fairbanks", "Fairbanks Uluslararası Havalimanı (FAI)"),
            new Location("ABD", "Fargo", "Hector Uluslararası Havalimanı (FAR)"),
            new Location("ABD", "Fayetteville", "Fayetteville Bölgesel (Grannis) Havalimanı (FAY)"),
            new Location("ABD", "Fayetteville/Springdale", "Northwest Arkansas Bölgesel Havalimanı (XNA)"),
            new Location("ABD", "Fort Lauderdale", "Fort Lauderdale–Hollywood Uluslararası Havalimanı (FLL)"),
            new Location("ABD", "Fort Myers", "Fort Myers Havalimanı (RSW)"),
            new Location("ABD", "Fort Wayne", "Fort Wayne Uluslararası Havalimanı (FWA)"),
            new Location("ABD", "Fresno", "Yosemite Uluslararası Havalimanı (FAT)"),
            new Location("ABD", "Grand Junction", "Grand Junction Bölgesel Havalimanı (GJT)"),
            new Location("ABD", "Grand Rapids", "Gerald R. Ford Uluslararası Havalimanı (GRR)"),
            new Location("ABD", "Great Falls", "Great Falls Uluslararası Havalimanı (GTF)"),
            new Location("ABD", "Green Bay", "Austin Straubel Uluslararası Havalimanı (GRB)"),
            new Location("ABD", "Greensboro/High Point", "Piedmont Triad Uluslararası Havalimanı (GSO)"),
            new Location("ABD", "Greenville", "Greenville Uluslararası Havalimanı (GSP)"),
            new Location("ABD", "Gulfport", "Gulfport/Biloxi Uluslararası Havalimanı (GPT)"),
            new Location("ABD", "Gunnison", "Gunnison-Crested Butte Havalimanı (GUC)"),
            new Location("ABD", "Hancock", "Houghton County Memorial Havalimanı (CMX)"),
            new Location("ABD", "Harlingen", "Valley Uluslararası Havalimanı (HRL)"),
            new Location("ABD", "Harrisburg", "Harrisburg Uluslararası Havalimanı (MDT)"),
            new Location("ABD", "Hartford", "Bradley Uluslararası Havalimanı (BDL)"),
            new Location("ABD", "Hayden", "Yampa Valley Havalimanı (HDN)"),
            new Location("ABD", "Hilo", "Hilo Uluslararası Havalimanı (ITO)"),
            new Location("ABD", "Honolulu", "Honolulu Uluslararası Havalimanı (HNL)"),
            new Location("ABD", "Houston", "George Bush Kıtalararası Havalimanı (IAH)"),
            new Location("ABD", "Houston", "William P. Hobby Havalimanı (HOU)"),
            new Location("ABD", "Huntsville", "Huntsville Uluslararası-Carl T. Jones Havalimanı (HSV)"),
            new Location("ABD", "Hyannis", "Barnstable Bölgesel Havalimanı (HYA)"),
            new Location("ABD", "Idaho Falls", "Idaho Falls Bölgesel Havalimanı (IDA)"),
            new Location("ABD", "Imperial/El Centro", "Imperial County Havalimanı (IPL)"),
            new Location("ABD", "Indianapolis", "Indianapolis Uluslararası Havalimanı (IND)"),
            new Location("ABD", "Inyokern", "Inyokern Havalimanı (IYK)"),
            new Location("ABD", "Ithaca", "Tompkins Bölgesel Havalimanı (ITH)"),
            new Location("ABD", "Jackson", "Jackson Hole Havalimanı (JAC)"),
            new Location("ABD", "Jackson", "Medgar W. Evers Ulusal Havalimanı (JAN)"),
            new Location("ABD", "Jacksonville", "Jacksonville Uluslararası Havalimanı (JAX)"),
            new Location("ABD", "Johnstown", "Johnstown Murtha-Cambria County Havalimanı (JST)"),
            new Location("ABD", "Juneau", "Juneau Havalimanı (JNU)"),
            new Location("ABD", "Kahului", "Kahului Havalimanı (OGG)"),
            new Location("ABD", "Kalamazoo", "Kalamazoo Airport (AZO)"),
            new Location("ABD", "Kalispell", "Kalispell Havalimanı (FCA)"),
            new Location("ABD", "Kansas City", "Kansas City Uluslararası Havalimanı (MCI)"),
            new Location("ABD", "Killeen/Fort Hood", "Killeen-Fort Hood Bölgesel Havalimanı (GRK)"),
            new Location("ABD", "Klamath Falls", "Klamath Falls Havalimanı (LMT)"),
            new Location("ABD", "Knoxville", "McGhee Tyson Havalimanı (TYS)"),
            new Location("ABD", "Kona", "Keahole Havalimanı (KOA)"),
            new Location("ABD", "Lafayette", "Lafayette Bölgesel Havalimanı (LFT)"),
            new Location("ABD", "Lake Charles", "Lake Charles Bölgesel Havalimanı (LCH)"),
            new Location("ABD", "Lansing", "Capital Region Uluslararası Havalimanı (LAN)"),
            new Location("ABD", "Laredo", "Laredo Uluslararası Havalimanı (LRD)"),
            new Location("ABD", "Las Vegas", "Las Vegas Mccarran Uluslararası Havalimanı (LAS)"),
            new Location("ABD", "Lexington", "Blue Grass Havalimanı (LEX)"),
            new Location("ABD", "Lihue", "Lihue Havalimanı (LIH)"),
            new Location("ABD", "Lincoln", "Lincoln Havalimanı (LNK)"),
            new Location("ABD", "Little Rock", "B. & H. Clinton Ulusal Havalimanı (LIT)"),
            new Location("ABD", "Long Beach", "Longbeach Havalimanı (LGB)"),
            new Location("ABD", "Los Angeles", "Los Angeles Uluslararası Havalimanı (LAX)"),
            new Location("ABD", "Louisville", "Uluslararası-Standiford Havalimanı (SDF)"),
            new Location("ABD", "Lubbock", "Preston Smith Uluslararası Havalimanı (LBB)"),
            new Location("ABD", "Madison", "Dane County Bölgesel Havalimanı (MSN)"),
            new Location("ABD", "Mammoth Lakes", "Mammoth Yosemite Havalimanı (MMH)"),
            new Location("ABD", "Manchester", "Manchester-Boston Bölgesel Havalimanı (MHT)"),
            new Location("ABD", "Martha's Vineyard", "Martha's Vineyard Havalimanı (MVY)"),
            new Location("ABD", "McAllen/Mission", "Miller Uluslararası Havalimanı (MFE)"),
            new Location("ABD", "Medford", "Rogue Valley Uluslararası Havalimanı (MFR)"),
            new Location("ABD", "Memphis", "Memphis Uluslararası Havalimanı (MEM)"),
            new Location("ABD", "Miami", "Miami Uluslararası Havalimanı (MIA)"),
            new Location("ABD", "Midland", "Midland Uluslararası Havalimanı (MAF)"),
            new Location("ABD", "Milwaukee", "General Mitchell Uluslararası Havalimanı (MKE)"),
            new Location("ABD", "Minneapolis", "Minneapolis-Saint Paul Uluslararası Havalimanı (MSP)"),
            new Location("ABD", "Missoula", "Missoula Uluslararası Havalimanı (MSO)"),
            new Location("ABD", "Mobile", "Mobile Bölgesel Havalimanı (MOB)"),
            new Location("ABD", "Modesto", "Modesto City-County Havalimanı (MOD)"),
            new Location("ABD", "Moline", "Quad City Uluslararası Havalimanı (MLI)"),
            new Location("ABD", "Monroe", "Monroe Bölgesel Havalimanı (MLU)"),
            new Location("ABD", "Monterey", "Monterey Bölgesel Havalimanı (MRY)"),
            new Location("ABD", "Montrose", "Montrose Bölgesel Havalimanı (MTJ)"),
            new Location("ABD", "Myrtle Beach", "Myrtle Beach Uluslararası Havalimanı (MYR)"),
            new Location("ABD", "Nantucket", "Memorial Havalimanı (ACK)"),
            new Location("ABD", "Nashville", "Nashville Havalimanı (BNA)"),
            new Location("ABD", "New Orleans", "Louis Armstrong Uluslararası Havalimanı (MSY)"),
            new Location("ABD", "New York", "John F. Kennedy Uluslararası Havalimanı (JFK)"),
            new Location("ABD", "New York", "Newark Liberty Uluslararası Havalimanı (EWR)"),
            new Location("ABD", "New York", "La Guardia Havalimanı (LGA)"),
            new Location("ABD", "New York", "Stewart Uluslararası Havalimanı (SWF)"),
            new Location("ABD", "Norfolk", "Norfolk Uluslararası Havalimanı (ORF)"),
            new Location("ABD", "North Bend", "Southwest Oregon Bölgesel Havalimanı (OTH)"),
            new Location("ABD", "Oakland", "Oakland Uluslararası Havalimanı (OAK)"),
            new Location("ABD", "Oklahoma City", "Will Rogers World Havalimanı (OKC)"),
            new Location("ABD", "Omaha", "Eppley Havalimanı (OMA)"),
            new Location("ABD", "Ontario", "Ontario Uluslararası Havalimanı (ONT)"),
            new Location("ABD", "Orlando", "Orlando Uluslararası Havalimanı (MCO)"),
            new Location("ABD", "Paducah", "Barkley Bölgesel Havalimanı (PAH)"),
            new Location("ABD", "Palm Springs", "Palm Springs Uluslararası Havalimanı (PSP)"),
            new Location("ABD", "Pasco", "Tri-Cities Havalimanı (PSC)"),
            new Location("ABD", "Pensacola", "Pensacola Uluslararası Havalimanı (PNS)"),
            new Location("ABD", "Peoria", "General Downing Uluslararası Havalimanı (PIA)"),
            new Location("ABD", "Philadelphia", "Philadelphia Uluslararası Havalimanı (PHL)"),
            new Location("ABD", "Phoenix", "Phoenix Sky Harbor Uluslararası Havalimanı (PHX)"),
            new Location("ABD", "Pittsburgh", "Pittsburgh Uluslararası Havalimanı (PIT)"),
            new Location("ABD", "Portland", "Portland Havalimanı (PDX)"),
            new Location("ABD", "Portland City", "Portland Uluslararası Jet Havalimanı (PWM)"),
            new Location("ABD", "Providence", "T.F. Green State Havalimanı (PVD)"),
            new Location("ABD", "Pullman/Moscow", "Pullman Havalimanı (PUW)"),
            new Location("ABD", "Raleigh Durham", "Raleigh-Durham Uluslararası Havalimanı (RDU)"),
            new Location("ABD", "Rapid City", "Rapid City Bölgesel Havalimanı (RAP)"),
            new Location("ABD", "Redding", "Redding Bölgesel Havalimanı (RDD)"),
            new Location("ABD", "Redmond/Bend", "Roberts Field Havalimanı (RDM)"),
            new Location("ABD", "Reno", "Reno/Tahoe Uluslararası Havalimanı (RNO)"),
            new Location("ABD", "Richmond", "Richmond Uluslararası Havalimanı (RIC)"),
            new Location("ABD", "Roanoke", "Roanoke Bölgesel (Woodrum) Havalimanı (ROA)"),
            new Location("ABD", "Rochester", "Rochester Uluslararası Havalimanı (ROC)"),
            new Location("ABD", "Sacramento", "Sacramento Uluslararası Havalimanı (SMF)"),
            new Location("ABD", "Saginaw/Midland/Bay City", "MBS Uluslararası Havalimanı (MBS)"),
            new Location("ABD", "Salt Lake City", "Salt Lake City Uluslararası Havalimanı (SLC)"),
            new Location("ABD", "San Antonio", "San Antonio Uluslararası Havalimanı (SAT)"),
            new Location("ABD", "San Diego", "San Diego Uluslararası Havalimanı (SAN)"),
            new Location("ABD", "San Francisco", "San Francisco Uluslararası Havalimanı (SFO)"),
            new Location("ABD", "San Jose", "Norman Y. Mineta Uluslararası Havalimanı (SJC)"),
            new Location("ABD", "San Luis Obispo", "San Luis County Bölgesel Havalimanı (SBP)"),
            new Location("ABD", "Santa Ana", "John Wayne Havalimanı (SNA)"),
            new Location("ABD", "Santa Barbara", "Santa Barbara Bölgesel Havalimanı (SBA)"),
            new Location("ABD", "Santa Maria", "Santa Maria Public Havalimanı (SMX)"),
            new Location("ABD", "Sarasota-Bradenton", "Sarasota-Bradenton Uluslararası Havalimanı (SRQ)"),
            new Location("ABD", "Savannah", "Hilton Head Uluslararası Havalimanı (SAV)"),
            new Location("ABD", "Seattle", "Seattle Tacoma Uluslararası Havalimanı (SEA)"),
            new Location("ABD", "Shreveport", "Shreveport Bölgesel Havalimanı (SHV)"),
            new Location("ABD", "South Bend", "South Bend Uluslararası Havalimanı (SBN)"),
            new Location("ABD", "Springfield", "Abraham Lincoln Capital Havalimanı (SPI)"),
            new Location("ABD", "Springfield", "Springfield-Branson Ulusal Havalimanı (SGF)"),
            new Location("ABD", "St. George", "St. George Bölgesel Havalimanı (SGU)"),
            new Location("ABD", "St. Louis", "Lambert-St. Louis Uluslararası Havalimanı (STL)"),
            new Location("ABD", "State College", "University Park Havalimanı (SCE)"),
            new Location("ABD", "Staunton/Waynesboro", "Shenandoah Valley Bölgesel Havalimanı (SHD)"),
            new Location("ABD", "Syracuse", "Hancock Uluslararası Havalimanı (SYR)"),
            new Location("ABD", "Şikago", "O'Hare Uluslararası Havalimanı (ORD)"),
            new Location("ABD", "Tampa", "Tampa Uluslararası Havalimanı (TPA)"),
            new Location("ABD", "Traverse City", "Cherry Capital Havalimanı (TVC)"),
            new Location("ABD", "Tucson", "Tucson Uluslararası Havalimanı (TUS)"),
            new Location("ABD", "Tulsa", "Tulsa Uluslararası Havalimanı (TUL)"),
            new Location("ABD", "Tyler", "Pounds Bölgesel Havalimanı (TYR)"),
            new Location("ABD", "Victoria", "Victoria Bölgesel Havalimanı (VCT)"),
            new Location("ABD", "Waco", "Waco Bölgesel Havalimanı (ACT)"),
            new Location("ABD", "Walla Walla", "Walla Walla Havalimanı (ALW)"),
            new Location("ABD", "Washington DC", "Dulles Uluslararası Havalimanı (IAD)"),
            new Location("ABD", "Washington DC", "Baltimore Washington Uluslararası Havalimanı (BWI)"),
            new Location("ABD", "Washington DC", "Ronald Reagan Ulusal Havalimanı (DCA)"),
            new Location("ABD", "Wausau", "Central Wisconsin Havalimanı (CWA)"),
            new Location("ABD", "Wenatchee", "Wenatchee Havalimanı (EAT)"),
            new Location("ABD", "West Palm Beach", "Palm Beach Uluslararası Havalimanı (PBI)"),
            new Location("ABD", "White Plains", "Westchester County Havalimanı (HPN)"),
            new Location("ABD", "Wichita", "Dwight D. Eisenhower Ulusal Havalimanı (ICT)"),
            new Location("ABD", "Williston", "Sloulin Field Uluslararası Havalimanı (ISN)"),
            new Location("ABD", "Worcester", "Worcester Bölgesel Havalimanı (ORH)"),
            new Location("ABD", "Yakima", "Yakima Havalimanı (YKM)"),
            new Location("ABD", "Yuma", "Yuma Uluslararası Havalimanı (YUM)"),
            new Location("Arjantin", "Buenos Aires", "Ministro Pistarini Uluslararası Havalimanı (EZE)"),
            new Location("Arjantin", "Buenos Aires", "Jorge Newbery Havalimanı (AEP)"),
            new Location("Arjantin", "Cordoba", "A. L. V. Taravella Havalimanı (COR)"),
            new Location("Arjantin", "El Calafate", "Comandante A. Tola Havalimanı (FTE)"),
            new Location("Arjantin", "Iguazu", "Cataratas del Iguazu Havalimanı (IGR)"),
            new Location("Arjantin", "Mendoza", "Mendoza Havalimanı (MDZ)"),
            new Location("Arjantin", "Rosario", "Islas Malvinas Havalimanı (ROS)"),
            new Location("Arjantin", "San Carlos Bariloche", "San Carlos Bariloche Havalimanı (BRC)"),
            new Location("Arjantin", "Ushuaia", "Ushuaia Havalimanı (USH)"),
            new Location("Arnavutluk", "Kukës", "Kökes Uluslararası Havalimanı (KFZ)"),
            new Location("Arnavutluk", "Tiran", "Tiran Uluslararası Havalimanı (TIA)"),
            new Location("Avustralya", "Adelaide", "Adelaide Uluslararası Havalimanı (ADL)"),
            new Location("Avustralya", "Brisbane", "Brisbane Havalimanı (BNE)"),
            new Location("Avustralya", "Cairns", "Cairns Uluslararası Havalimanı (CNS)"),
            new Location("Avustralya", "Canberra", "Canberra Havalimanı (CBR)"),
            new Location("Avustralya", "Darwin", "Darwin Uluslararası Havalimanı (DRW)"),
            new Location("Avustralya", "Gold Coast", "Coolangatta Havalimanı (OOL)"),
            new Location("Avustralya", "Hobart", "Hobart Uluslararası Havalimanı (HBA)"),
            new Location("Avustralya", "Launceston", "Launceston Havalimanı (LST)"),
            new Location("Avustralya", "Mackay", "Mackay Havalimanı (MKY)"),
            new Location("Avustralya", "Melbourne", "Avalon Havalimanı (AVV)"),
            new Location("Avustralya", "Melbourne", "Melbourne-Tullamarine Uluslararası Havalimanı (MEL)"),
            new Location("Avustralya", "Newcastle", "Williamtown Havalimanı (NTL)"),
            new Location("Avustralya", "Perth", "Perth Havalimanı (PER)"),
            new Location("Avustralya", "Port Lincoln", "Port Lincoln Havalimanı (PLO)"),
            new Location("Avustralya", "Proserpine", "Whitsunday Coast Havalimanı (PPP)"),
            new Location("Avustralya", "Sidney", "Sydney Kingsford Smith Havalimanı (SYD)"),
            new Location("Avustralya", "Sunshine Coast", "Sunshine Coast Havalimanı (MCY)"),
            new Location("Avustralya", "Tsewi", "Tsewi Havalimanı (TSW)"),
            new Location("Avusturya", "Bregenz", "Bregenz Merkez Tren İstasyonu (XGZ)"),
            new Location("Avusturya", "Graz", "Graz Havalimanı (GRZ)"),
            new Location("Avusturya", "Graz", "Graz Merkerz Tren İstasyonu (GGZ)"),
            new Location("Avusturya", "Innsbruck", "Innsbruck Merkez Tren İstasyonu (IOB)"),
            new Location("Avusturya", "Linz", "Linz Tren İstasyonu (LZS)"),
            new Location("Avusturya", "Saint Pölten", "St. Pölten Tren İstasyonu (POK)"),
            new Location("Avusturya", "Salzburg", "Salzburg W. A. Mozart Havalimanı (SZG)"),
            new Location("Avusturya", "Salzburg", "Salzburg Merkez Tren İstasyonu (ZSB)"),
            new Location("Avusturya", "Viyana", "Viyana Schwechat Havalimanı (VIE)"),
            new Location("Azerbeycan", "Bakü", "Haydar Aliyev Uluslararası Havalimanı (GYD)"),
            new Location("Azerbeycan", "Gence", "Gence Havalimanı (GNJ)"),
            new Location("Azerbeycan", "Nahçıvan", "Nahçıvan Havalimanı (NAJ)"),
            new Location("Belçika", "Antwerp", "Antwerp-Centraal Tren İstasyonu (ZWE)"),
            new Location("Belçika", "Brüksel", "Brüksel National Havalimanı (BRU)"),
            new Location("Birleşik Krallık", "Aberdeen", "Aberdeen Dyce Havalimanı (ABZ)"),
            new Location("Birleşik Krallık", "Birmingham", "Birmingham Havalimanı (BHX)"),
            new Location("Birleşik Krallık", "Bridgwater", "Bridgwater Tren İstasyonu (UBW)"),
            new Location("Birleşik Krallık", "Brighton", "Brighton Tren İstasyonu (BSH)"),
            new Location("Birleşik Krallık", "Bristol", "Bristol Havalimanı (BRS)"),
            new Location("Birleşik Krallık", "Cambridge", "Cambridge Tren İstasyonu (CBG)"),
            new Location("Birleşik Krallık", "Cardiff", "Cardiff Havalimanı (CWL)"),
            new Location("Birleşik Krallık", "Cardiff", "Cardiff Merkez Tren İstasyonu (CFW)"),
            new Location("Birleşik Krallık", "Coventry", "Coventry Tren İstasyonu (CVT)"),
            new Location("Birleşik Krallık", "Durham", "Teesside Uluslararası Havalimanı (MME)"),
            new Location("Birleşik Krallık", "Edinburg", "Edinburgh Havalimanı (EDI)"),
            new Location("Birleşik Krallık", "Exeter", "Exeter Tren İstasyonu (EXS)"),
            new Location("Birleşik Krallık", "Falmouth", "Falmouth Tren İstasyonu (UFM)"),
            new Location("Birleşik Krallık", "Glasgow", "Glasgow Uluslararası Havalimanı (GLA)"),
            new Location("Birleşik Krallık", "Gloucester", "Gloucester Tren İstasyonu (GLO)"),
            new Location("Birleşik Krallık", "Hereford", "Hereford Tren İstasyonu (HFH)"),
            new Location("Birleşik Krallık", "Inverness", "Inverness Havalimanı (INV)"),
            new Location("Birleşik Krallık", "Londra", "Gatwick Havalimanı (LGW)"),
            new Location("Birleşik Krallık", "Londra", "Heathrow Havalimanı (LHR)"),
            new Location("Birleşik Krallık", "Londra", "London Stansted Havalimanı (STN)"),
            new Location("Birleşik Krallık", "Man Adası", "Man Adası Havalimanı (IOM)"),
            new Location("Birleşik Krallık", "Manchester", "Manchester Havalimanı (MAN)"),
            new Location("Birleşik Krallık", "Milton Keynes", "Milton Keynes Central Tren İstasyonu (KYN)"),
            new Location("Birleşik Krallık", "Newcastle", "Newcastle Uluslararası Havalimanı (NCL)"),
            new Location("Birleşik Krallık", "Newport", "Newport Tren İstasyonu (XNE)"),
            new Location("Birleşik Krallık", "Orkney Adaları", "Kirkwall Havalimanı (KOI)"),
            new Location("Birleşik Krallık", "Par", "Par Tren İstasyonu (PCW)"),
            new Location("Birleşik Krallık", "Penzance", "Penzance Tren İstasyonu (PZE)"),
            new Location("Birleşik Krallık", "Plymouth", "Plymouth Tren İstasyonu (PLH)"),
            new Location("Birleşik Krallık", "Shetland Adaları", "Sumburgh Havalimanı (LSI)"),
            new Location("Birleşik Krallık", "Southampton", "Southampton Havalimanı (SOU)"),
            new Location("Birleşik Krallık", "St. Austell", "St. Austell Tren İstasyonu (USX)"),
            new Location("Birleşik Krallık", "Stornoway", "Stornoway Havalimanı (SYY)"),
            new Location("Birleşik Krallık", "Swansea", "Swansea Tren İstasyonu (SWS)"),
            new Location("Birleşik Krallık", "Worcester", "Worcester Tren İstasyonu (UWC)"),
            new Location("Bosna-Hersek", "Banja Luka", "Banja Luka Havalimanı (BNX)"),
            new Location("Bosna-Hersek", "Saraybosna", "Saraybosna Uluslararası Havalimanı (SJJ)"),
            new Location("Brezilya", "Aracaju", "Santa Maria Havalimanı (AJU)"),
            new Location("Brezilya", "Belem", "Val de Cans Uluslararası Havalimanı (BEL)"),
            new Location("Brezilya", "Belo Horizonte", "Tancredo Neves Uluslararası Havalimanı (CNF)"),
            new Location("Brezilya", "Brazilya", "Juscelino Kubitschek Uluslararası Havalimanı (BSB)"),
            new Location("Brezilya", "CAMPINA GRANDE", "CAMPINA GRANDE (CPV)"),
            new Location("Brezilya", "Campinas", "Viracopos-Campinos Uluslararası Havalimanı (VCP)"),
            new Location("Brezilya", "Campo Grande", "Campo Grande Uluslararası Havalimanı (CGR)"),
            new Location("Brezilya", "Chapecó", "Serafin Enoss Bertaso Havalimanı (XAP)"),
            new Location("Brezilya", "Cuiaba", "Marechal Rondon Uluslararası Havalimanı (CGB)"),
            new Location("Brezilya", "Curitiba", "Afonso Pena Uluslararası Havalimanı (CWB)"),
            new Location("Brezilya", "Florianopolis", "Hercilio Luz Uluslararası Havalimanı (FLN)"),
            new Location("Brezilya", "Fortaleza", "Pinto Martins Uluslararası Havalimanı (FOR)"),
            new Location("Brezilya", "Foz do Iguacu", "Foz do Iguacu/Cataratas Uluslararası Havalimanı (IGU)"),
            new Location("Brezilya", "Goiania", "Santa Genoveva Havalimanı (GYN)"),
            new Location("Brezilya", "Ilheus", "Jorge Amado Havalimanı (IOS)"),
            new Location("Brezilya", "Imperatriz", "Renato Moreira Havalimanı (IMP)"),
            new Location("Brezilya", "Joao Pessoa", "Castro Pinto Uluslararası Havalimanı (JPA)"),
            new Location("Brezilya", "Joinville", "Lauro Carneiro Loyola Havalimanı (JOI)"),
            new Location("Brezilya", "Juazeiro do Norte", "Orlando Bezerra de Menezes Havalimanı (JDO)"),
            new Location("Brezilya", "Londrina", "Jose Richa Havalimanı (LDB)"),
            new Location("Brezilya", "Maceio", "Zumbi dos Palmares Uluslararası Havalimanı (MCZ)"),
            new Location("Brezilya", "Manaus", "Eduardo Gomes Uluslararası Havalimanı (MAO)"),
            new Location("Brezilya", "Maringá", "Sílvio Name Júnior Bölgesel Havalimanı (MGF)"),
            new Location("Brezilya", "Montes Claros", "Montes Claros/Mário Ribeiro Havalimanı (MOC)"),
            new Location("Brezilya", "Natal", "Natal Uluslararası Havalimanı (NAT)"),
            new Location("Brezilya", "Navegantes", "Victor Konder Uluslararası Havalimanı (NVT)"),
            new Location("Brezilya", "Palmas", "Lysias Rodrigues Havalimanı (PMW)"),
            new Location("Brezilya", "Passo Fundo", "Lauro Kurtz Havalimanı (PFB)"),
            new Location("Brezilya", "Porto Alegre", "Salgado Filho Uluslararası Havalimanı (POA)"),
            new Location("Brezilya", "Porto Seguro", "Porto Seguro Havalimanı (BPS)"),
            new Location("Brezilya", "Recife", "Guararapes Uluslararası Havalimanı (REC)"),
            new Location("Brezilya", "Ribeirao Preto", "Leite Lopes Havalimanı (RAO)"),
            new Location("Brezilya", "Rio Branco", "Placido de Castro Havalimanı (RBR)"),
            new Location("Brezilya", "Rio de Janeiro", "Galeao Antonio Carlos Jobim Uluslararası Havalimanı (GIG)"),
            new Location("Brezilya", "Rio De Janeiro", "Santos Dumont Havalimanı (SDU)"),
            new Location("Brezilya", "Salvador", "Luis Eduardo Magalhaes Uluslararası Havalimanı (SSA)"),
            new Location("Brezilya", "São José Do Rio Preto", "Eribelto Manoel Reino Havalimanı (SJP)"),
            new Location("Brezilya", "Sao Luis", "Cunha Machado Uluslararası Havalimanı (SLZ)"),
            new Location("Brezilya", "Sao Paulo", "(SAO)"),
            new Location("Brezilya", "Sao Paulo", "Sao Paulo Guarulhos Havalimanı (GRU)"),
            new Location("Brezilya", "Sao Paulo", "Congonhas Havalimanı (CGH)"),
            new Location("Brezilya", "Teresina", "Senador Petrônio Portella Havalimanı (THE)"),
            new Location("Brezilya", "Uberlandia", "Cesar Bombonato Havalimanı (UDI)"),
            new Location("Brezilya", "Vitoria", "Eurico de Aguiar Salles Havalimanı (VIX)"),
            new Location("Bulgaristan", "Sofya", "Sofya Havalimanı (SOF)"),
            new Location("Bulgaristan", "Varna", "Varna Havalimanı (VAR)"),
            new Location("Danimarka", "Aalborg", "Aalborg Havalimanı (AAL)"),
            new Location("Danimarka", "Aarhus", "Aarhus Havalimanı (AAR)"),
            new Location("Danimarka", "Billund", "Billund Havalimanı (BLL)"),
            new Location("Danimarka", "Kopenhag", "Kopenhag Kastrup Havalimanı (CPH)"),
            new Location("Finlandiya", "Helsinki", "Helsinki-Vantaa Havalimanı (HEL)"),
            new Location("Finlandiya", "Ivalo", "Ivalo Havalimanı (IVL)"),
            new Location("Finlandiya", "Joensuu", "Joensuu Havalimanı (JOE)"),
            new Location("Finlandiya", "Jyvaskyla", "Jyvaskyla Havalimanı (JYV)"),
            new Location("Finlandiya", "Kajaani", "Kajaani Havalimanı (KAJ)"),
            new Location("Finlandiya", "Kemi", "Kemi Havalimanı (KEM)"),
            new Location("Finlandiya", "Kittila", "Kittila Havalimanı (KTT)"),
            new Location("Finlandiya", "Kokkola", "Kokkola Havalimanı (KOK)"),
            new Location("Finlandiya", "Kuopio", "Kuopio Havalimanı (KUO)"),
            new Location("Finlandiya", "Kuusamo", "Kuusamo Havalimanı (KAO)"),
            new Location("Finlandiya", "Mariehamn", "Mariehamn Havalimanı (MHQ)"),
            new Location("Finlandiya", "Oulu", "Oulu Havalimanı (OUL)"),
            new Location("Finlandiya", "Rovaniemi", "Rovaniemi Havalimanı (RVN)"),
            new Location("Finlandiya", "Tampere", "Tampere-Pirkkala Havalimanı (TMP)"),
            new Location("Finlandiya", "Turku", "Turku Havalimanı (TKU)"),
            new Location("Finlandiya", "Vaasa", "Vaasa Havalimanı (VAA)"),
            new Location("Fransa", "Bordo", "Bordeaux-Merignac Havalimanı (BOD)"),
            new Location("Fransa", "Lille", "Lille Lesquin Havalimanı (LIL)"),
            new Location("Fransa", "Lyon", "Saint Exupery Havalimanı (LYS)"),
            new Location("Fransa", "Marsilya", "Marsilya Provence (Marignane) Havalimanı (MRS)"),
            new Location("Fransa", "Metz/Nancy", "Metz/Nancy Lorraine Havalimanı (ETZ)"),
            new Location("Fransa", "Montpellier", "Mediterranee Havalimanı (MPL)"),
            new Location("Fransa", "Nice", "Cote D'Azur Uluslararası Havalimanı (NCE)"),
            new Location("Fransa", "Paris", "Charles De Gaulle Havalimanı (CDG)"),
            new Location("Fransa", "Strasbourg", "Strasbourg Havalimanı (SXB)"),
            new Location("Fransa", "Toulouse", "Toulouse Blagnac Havalimanı (TLS)"),
            new Location("Güney Kore", "Busan", "Gimhae Uluslararası Havalimanı (PUS)"),
            new Location("Güney Kore", "Jeju", "Jeju Uluslararası Havalimanı (CJU)"),
            new Location("Güney Kore", "Seoul", "Seoul Gimpo Uluslararası Havalimanı (GMP)"),
            new Location("Güney Kore", "Seul", "Incheon Uluslararası Havalimanı (ICN)"),
            new Location("İspanya", "A Coruna", "A Coruna Havalimanı (LCG)"),
            new Location("İspanya", "Albacete", "Albacete Havalimanı Tren İstasyonu (EEM)"),
            new Location("İspanya", "ALİCANTE", "Alicante Havalimanı (ALC)"),
            new Location("İspanya", "Alicante", "Alicante Havalimanı Tren İstasyonu (YJE)"),
            new Location("İspanya", "Almeria", "Almeria Tren İstasyonu (AMR)"),
            new Location("İspanya", "Almeria", "Almeria Havalimanı (LEI)"),
            new Location("İspanya", "Balear Adaları", "Ibiza Havalimanı (IBZ)"),
            new Location("İspanya", "Balear Adaları", "Palma de Mallorca Havalimanı (PMI)"),
            new Location("İspanya", "Barselona", "Barselona El Prat Havalimanı (BCN)"),
            new Location("İspanya", "Bilbao", "Bilbao Havalimanı (BIO)"),
            new Location("İspanya", "Burgos", "Burgos Tren İstasyonu (UGR)"),
            new Location("İspanya", "Cádiz", "Cádiz Tren İstasyonu (CDZ)"),
            new Location("İspanya", "Castellon", "Castellon Tren İstasyonu (CPJ)"),
            new Location("İspanya", "Fuerteventura", "Fuerteventura Havalimanı (FUE)"),
            new Location("İspanya", "Girona", "Girona Costa Brava Havalimanı Tren İstasyonu (GIA)"),
            new Location("İspanya", "Granada", "Granada Tren İstasyonu (YJG)"),
            new Location("İspanya", "Granada", "Granada Havalimanı (GRX)"),
            new Location("İspanya", "Huelva", "Huelva Tren İstasyonu (HEV)"),
            new Location("İspanya", "Jerez De La Frontera", "Jerez De La Frontera Tren İstasyonu (YJW)"),
            new Location("İspanya", "Jerez De La Frontera", "Jerez Havalimanı (XRY)"),
            new Location("İspanya", "Kanarya Adaları", "Gran Canaria Havalimanı (LPA)"),
            new Location("İspanya", "Lanzarote", "Lanzarote Havalimanı (ACE)"),
            new Location("İspanya", "Leon", "Leon Tren İstasyonu (EEU)"),
            new Location("İspanya", "Lleida", "Lleida Pirineus Tren İstasyonu (QLQ)"),
            new Location("İspanya", "Madrid", "Madrid Barajas Uluslararası Havalimanı (MAD)"),
            new Location("İspanya", "Malaga", "Malaga Costa Del Sol Havalimanı (AGP)"),
            new Location("İspanya", "Menorca", "Menorca Havalimanı (MAH)"),
            new Location("İspanya", "Murcia", "Murcia Del Carmen Tren İstasyonu (XUT)"),
            new Location("İspanya", "Oviedo", "Oviedo Tren İstasyonu (OVI)"),
            new Location("İspanya", "OVİEDO", "Asturias Havalimanı (OVD)"),
            new Location("İspanya", "Palencia", "Palencia Tren İstasyonu (PCI)"),
            new Location("İspanya", "Pamplona", "Pamplona Tren İstasyonu (EEP)"),
            new Location("İspanya", "SAN SEBASTIAN", "San Sebastian Havalimanı (EAS)"),
            new Location("İspanya", "Santiago de Compostela", "Santiago De Compostela Havalimanı (SCQ)"),
            new Location("İspanya", "Sevilla", "Sevilla Havalimanı (SVQ)"),
            new Location("İspanya", "Tenerife", "Tenerife Kuzey Havalimanı (TFN)"),
            new Location("İspanya", "Tenerife", "Tenerife Sur Havalimanı (TFS)"),
            new Location("İspanya", "Valensiya", "Valensiya Havalimanı (VLC)"),
            new Location("İspanya", "Vigo", "Vigo Havalimanı (VGO)"),
            new Location("İspanya", "Vitoria-Gasteiz", "Vitoria-Gasteiz Tren İstasyonu (VIO)"),
            new Location("İspanya", "Zaragoza", "Zaragoza-Delicias Tren İstasyonu (XZZ)"),
            new Location("İtalya", "Bari", "Bari/Palese Uluslararası Havalimanı (BRI)"),
            new Location("İtalya", "Bologna", "Bologna Guglielmo Marconi Havalimanı (BLQ)"),
            new Location("İtalya", "Cagliari", "Elmas Havalimanı (CAG)"),
            new Location("İtalya", "Cenova", "Cenova Cristoforo Colombo Havalimanı (GOA)"),
            new Location("İtalya", "Floransa", "Floransa Peretola Havalimanı (FLR)"),
            new Location("İtalya", "Katanya", "Katanya Fontanarossa Havalimanı (CTA)"),
            new Location("İtalya", "Milano", "Milano Bergamo Havalimanı (BGY)"),
            new Location("İtalya", "Milano", "Milano Malpensa Havalimanı (MXP)"),
            new Location("İtalya", "Milano", "Linate Havalimanı (LIN)"),
            new Location("İtalya", "Napoli", "Napoli Uluslararası Havalimanı (NAP)"),
            new Location("İtalya", "Olbia", "Costa Smeralda Havalimanı (OLB)"),
            new Location("İtalya", "Palermo", "Punta Raisi Havalimanı (PMO)"),
            new Location("İtalya", "Pisa", "Pisa Galileo Galilei Havalimanı (PSA)"),
            new Location("İtalya", "Roma", "Fiumicino – Leonardo da Vinci Havalimanı (FCO)"),
            new Location("İtalya", "Roma", "Ciampino Havalimanı (CIA)"),
            new Location("İtalya", "Torino", "Torino Havalimanı (TRN)"),
            new Location("İtalya", "Trieste", "TRIESTE (TRS)"),
            new Location("İtalya", "Venedik", "Venedik Marco Polo Havalimanı (VCE)"),
            new Location("Japonya", "Akita", "Akita Havalimanı (AXT)"),
            new Location("Japonya", "Amami", "Amami O Shima Havalimanı (ASJ)"),
            new Location("Japonya", "Aomori", "Aomori Havalimanı (AOJ)"),
            new Location("Japonya", "Asahikawa", "Asahikawa Havalimanı (AKJ)"),
            new Location("Japonya", "Fukuoka", "Fukuoka Havalimanı (FUK)"),
            new Location("Japonya", "Hakodate", "Hakodate Havalimanı (HKD)"),
            new Location("Japonya", "Hanamaki", "Hanamaki Havalimanı (HNA)"),
            new Location("Japonya", "Hiroşima", "Hiroşima Havalimanı (HIJ)"),
            new Location("Japonya", "Ishigaki", "New Ishigaki Havalimanı (ISG)"),
            new Location("Japonya", "Izumo", "Izumo Havalimanı (IZO)"),
            new Location("Japonya", "Kagoshima", "Kagoshima Havalimanı (KOJ)"),
            new Location("Japonya", "Kitaky?sh?", "Kita Kyushu Havalimanı (KKJ)"),
            new Location("Japonya", "Kochi", "Kochi Havalimanı (KCZ)"),
            new Location("Japonya", "Komatsu", "Komatsu Havalimanı (KMQ)"),
            new Location("Japonya", "Kumamoto", "Kumamoto Havalimanı (KMJ)"),
            new Location("Japonya", "Kushiro", "Kushiro Havalimanı (KUH)"),
            new Location("Japonya", "Matsuyama", "Matsuyama Havalimanı (MYJ)"),
            new Location("Japonya", "Memanbetsu", "Memambetsu Havalimanı (MMB)"),
            new Location("Japonya", "Misawa", "Misawa Havalimanı (MSJ)"),
            new Location("Japonya", "Miyako Jima", "Miyako Havalimanı (MMY)"),
            new Location("Japonya", "Miyazaki", "Miyazaki Havalimanı (KMI)"),
            new Location("Japonya", "Nagasaki", "Nagasaki Havalimanı (NGS)"),
            new Location("Japonya", "Nagoya", "Nagoya Havalimanı (NGO)"),
            new Location("Japonya", "Niigata", "Niigata Havalimanı (KIJ)"),
            new Location("Japonya", "Obihiro", "Obihiro Havalimanı (OBO)"),
            new Location("Japonya", "Oita", "Oita Havalimanı (OIT)"),
            new Location("Japonya", "Okayama", "Okayama Havalimanı (OKJ)"),
            new Location("Japonya", "Okinawa", "Naha Havalimanı (OKA)"),
            new Location("Japonya", "Osaka", "Kansai Uluslararası Havalimanı (KIX)"),
            new Location("Japonya", "Osaka", "Itami Havalimanı (ITM)"),
            new Location("Japonya", "Osaka", "Osaka Kobe Havalimanı (UKB)"),
            new Location("Japonya", "Saga", "Saga Havalimanı (HSG)"),
            new Location("Japonya", "Sapporo", "New Chitose Havalimanı (CTS)"),
            new Location("Japonya", "Sendai", "Sendai Havalimanı (SDJ)"),
            new Location("Japonya", "Shirahama", "Nanki Shirahama Havalimanı (SHM)"),
            new Location("Japonya", "Takamatsu", "Takamatsu Havalimanı (TAK)"),
            new Location("Japonya", "Tokushima", "Tokushima Havalimanı (TKS)"),
            new Location("Japonya", "Tokyo", "Narita Uluslararası Havalimanı (NRT)"),
            new Location("Japonya", "Tokyo", "Haneda Uluslararası Havalimanı (HND)"),
            new Location("Japonya", "Toyama", "Toyama Havalimanı (TOY)"),
            new Location("Japonya", "Ube", "Ube Havalimanı (UBJ)"),
            new Location("Japonya", "Yamagata", "Yamagata Havalimanı (GAJ)"),
            new Location("Kanada", "Abbotsford", "Abbotsford Uluslararası Havalimanı (YXX)"),
            new Location("Kanada", "Bagotville", "Bagotville Havalimanı (YBG)"),
            new Location("Kanada", "Bathurst", "Bathurst Havalimanı (ZBF)"),
            new Location("Kanada", "Calgary", "Calgary Havalimanı (YYC)"),
            new Location("Kanada", "Charlottetown", "Charlottetown Havalimanı (YYG)"),
            new Location("Kanada", "Deer Lake", "Deer Lake Bölgesel Havalimanı (YDF)"),
            new Location("Kanada", "Edmonton", "Edmonton Uluslararası Havalimanı (YEG)"),
            new Location("Kanada", "Fort McMurray", "Fort McMurray Havalimanı (YMM)"),
            new Location("Kanada", "Fort St.John", "North Peace Havalimanı (YXJ)"),
            new Location("Kanada", "Fredericton", "Fredericton Uluslararası Havalimanı (YFC)"),
            new Location("Kanada", "Gander", "Gander Uluslararası Havalimanı (YQX)"),
            new Location("Kanada", "Grande Prairie", "Grande Prairie Havalimanı (YQU)"),
            new Location("Kanada", "Halifax", "Halifax Stanfield Uluslararası Havalimanı (YHZ)"),
            new Location("Kanada", "Hamilton", "John C. Munro Hamilton Havalimanı (YHM)"),
            new Location("Kanada", "Iles de la Madeleine", "Iles de la Madeleine Havalimanı (YGR)"),
            new Location("Kanada", "Kamloops", "Kamloops Havalimanı (YKA)"),
            new Location("Kanada", "Kelowna", "Kelowna Uluslararası Havalimanı (YLW)"),
            new Location("Kanada", "Kingston", "Norman Rogers Havalimanı (YGK)"),
            new Location("Kanada", "London", "London Uluslararası Havalimanı (YXU)"),
            new Location("Kanada", "Moncton", "Greater Moncton Uluslararası Havalimanı (YQM)"),
            new Location("Kanada", "Mont-Joli", "Mont-Joli Havalimanı (YYY)"),
            new Location("Kanada", "Montreal", "Montreal–Pierre Elliott Trudeau Uluslararası Havalimanı (YUL)"),
            new Location("Kanada", "North Bay", "Jack Garland Havalimanı (YYB)"),
            new Location("Kanada", "Ottawa", "Ottawa Macdonald-Cartier Uluslararası Havalimanı (YOW)"),
            new Location("Kanada", "Quebec", "Quebec Jean Lesage Uluslararası Havalimanı (YQB)"),
            new Location("Kanada", "Red Deer", "Red Deer Regional Havalimanı (YQF)"),
            new Location("Kanada", "Regina", "Regina Uluslararası Havalimanı (YQR)"),
            new Location("Kanada", "Rouyn-Noranda", "Rouyn-Noranda Havalimanı (YUY)"),
            new Location("Kanada", "Saint John", "Saint John Havalimanı (YSJ)"),
            new Location("Kanada", "Sarnia", "Chris Hadfield Havalimanı (YZR)"),
            new Location("Kanada", "Saskatoon", "John G. Diefenbaker Uluslararası Havalimanı (YXE)"),
            new Location("Kanada", "Sault Ste. Marie", "Sault Ste. Marie Havalimanı (YAM)"),
            new Location("Kanada", "Sept Iles", "Sept-Iles Havalimanı (YZV)"),
            new Location("Kanada", "Sidney", "J. A. Douglas McCurdy Havalimanı (YQY)"),
            new Location("Kanada", "St. John's", "St. John's Uluslararası Havalimanı (YYT)"),
            new Location("Kanada", "Sudbury", "Sudbury Havalimanı (YSB)"),
            new Location("Kanada", "Thunder Bay", "Thunder Bay Uluslararası Havalimanı (YQT)"),
            new Location("Kanada", "Timmins", "Victor M. Power Havalimanı (YTS)"),
            new Location("Kanada", "Toronto", "Toronto Lester B. Pearson Uluslararası Havalimanı (YYZ)"),
            new Location("Kanada", "Toronto", "Billy Bishop Şehir Havalimanı (YTZ)"),
            new Location("Kanada", "Val d'Or", "Val d'Or Havalimanı (YVO)"),
            new Location("Kanada", "Vancouver", "Vancouver Uluslararası Havalimanı (YVR)"),
            new Location("Kanada", "Victoria", "Victoria Uluslararası Havalimanı (YYJ)"),
            new Location("Kanada", "Whitehorse", "Erik Nielsen Uluslararası Havalimanı (YXY)"),
            new Location("Kanada", "Windsor", "Windsor Havalimanı (YQG)"),
            new Location("Kanada", "Winnipeg", "James Armstrong Richards Uluslararası Havalimanı (YWG)"),
            new Location("Kazakistan", "Aktav", "Aktav Havalimanı (SCO)"),
            new Location("Kazakistan", "Almatı", "Almatı Havalimanı (ALA)"),
            new Location("Kazakistan", "Astana", "Nursultan Nazarbayev Uluslararası Havalimanı (NQZ)"),
            new Location("Kazakistan", "Türkistan", "Hazret Sultan Uluslararası Havalimanı (HSA)"),
            new Location("Kırgızistan", "Bişkek", "Manas Uluslararası Havalimanı (FRU)"),
            new Location("Kuzey Kıbrıs Türk Cumhuriyeti", "Lefkoşa", "Ercan Uluslararası Havalimanı (ECN)"),
            new Location("Meksika", "Acapulco", "General Juan N. Alvarez Uluslararası Havalimanı (ACA)"),
            new Location("Meksika", "Aguascalientes", "Aguascalientes Airport (AGU)"),
            new Location("Meksika", "Cancun", "Cancun Havalimanı (CUN)"),
            new Location("Meksika", "Ciudad Victoria", "General Pedro José Méndez Uluslararası Havalimanı (CVM)"),
            new Location("Meksika", "Colima", "Colima Havalimanı (CLQ)"),
            new Location("Meksika", "Cozumel", "Cozumel Uluslararası Havalimanı (CZM)"),
            new Location("Meksika", "Ixtepec", "Ixtepec Havalimanı (IZT)"),
            new Location("Meksika", "Lazaro Cardenas", "Lâzaro Cârdenas Havalimanı (LZC)"),
            new Location("Meksika", "Leon/Guanajuato", "Del Bajio Uluslararası Havalimanı (BJX)"),
            new Location("Meksika", "Mexico City", "Benito Juarez Uluslararası Havalimanı (MEX)"),
            new Location("Meksika", "Monterrey", "Mariano Escobedo Uluslararası Havalimanı (MTY)"),
            new Location("Meksika", "Oaxaca", "Oaxaca Uluslararası Havalimanı (OAX)"),
            new Location("Meksika", "Piedras Negras", "Piedras Negras Havalimanı (PDS)"),
            new Location("Meksika", "Poza Rica", "El Tajin National Havalimanı (PAZ)"),
            new Location("Meksika", "Puerto Escondido", "Puerto Escondido Uluslararası Havalimanı (PXM)"),
            new Location("Meksika", "Puerto Vallarta", "Gustavo Diaz Ordaz Uluslararası Havalimanı (PVR)"),
            new Location("Meksika", "San José del Cabo", "Los Cabos Uluslararası Havalimanı (SJD)"),
            new Location("Meksika", "San Luis Potosi", "San Luis Potosi Uluslararası Havalimanı (SLP)"),
            new Location("Meksika", "Tepic", "Tepic Havalimanı (TPQ)"),
            new Location("Meksika", "Veracruz", "Veracruz Havalimanı (VER)"),
            new Location("Meksika", "Zihuatanejo", "Ixtapa/Zihuatanejo Havalimanı (ZIH)"),
            new Location("Norveç", "Alesund", "Alesund Vigra Havalimanı (AES)"),
            new Location("Norveç", "Alta", "Alta Havalimanı (ALF)"),
            new Location("Norveç", "Bergen", "Bergen Flesland Havalimanı (BGO)"),
            new Location("Norveç", "Bodo", "Bodo Havalimanı (BOO)"),
            new Location("Norveç", "Harstad-Narvik", "Evenes Havalimanı (EVE)"),
            new Location("Norveç", "Haugesund", "Haugesund Karmoy Havalimanı (HAU)"),
            new Location("Norveç", "Kirkenes", "Hoybuktmoen Havalimanı (KKN)"),
            new Location("Norveç", "Kristiansand", "Kristiansand Kjevik Havalimanı (KRS)"),
            new Location("Norveç", "Kristiansund", "Kristiansund Kvernberget Havalimanı (KSU)"),
            new Location("Norveç", "Longyearbyen", "Svalbard Airport (LYR)"),
            new Location("Norveç", "Molde", "Molde Havalimanı (MOL)"),
            new Location("Norveç", "Oslo", "Oslo-Gardermoen Havalimanı (OSL)"),
            new Location("Norveç", "Stavanger", "Stavanger Sola Havalimanı (SVG)"),
            new Location("Norveç", "Tromsö", "Tromsö Havalimanı (TOS)"),
            new Location("Norveç", "Trondheim", "Trondheim Vaernes Havalimanı (TRD)"),
            new Location("Özbekistan", "Buhara", "Buhara Havalimanı (BHK)"),
            new Location("Özbekistan", "Fergana", "Fergana Havalimanı (FEG)"),
            new Location("Özbekistan", "Navoi", "Navoi International Airport (NVI)"),
            new Location("Özbekistan", "Semerkant", "Semerkant Uluslararası Havalimanı (SKD)"),
            new Location("Özbekistan", "Taşkent", "Taşkent Uluslararası Havalimanı (TAS)"),
            new Location("Özbekistan", "Termez", "Termez Havalimanı (TMJ)"),
            new Location("Özbekistan", "Ürgenç", "Ürgenç Havalimanı (UGC)"),
            new Location("Polonya", "Gdańsk", "Lech Walesa Havalimanı (GDN)"),
            new Location("Polonya", "Katowice", "Katowice Havalimanı (KTW)"),
            new Location("Polonya", "Krakow", "Krakow II. John Paul Uluslararası Havalimanı (KRK)"),
            new Location("Polonya", "Poznan", "Lawica Havalimanı (POZ)"),
            new Location("Polonya", "Rzeszow", "Rzeszow Havalimanı (RZE)"),
            new Location("Polonya", "Szczecin", "Szczecin Havalimanı (SZZ)"),
            new Location("Polonya", "Varşova", "Varşova Frederic Chopin Havalimanı (WAW)"),
            new Location("Polonya", "Wrocław", "Nicolaus Copernicus Havalimanı (WRO)"),
            new Location("Polonya", "Zielona Gora", "Zielona Gora Havalimanı (IEG)"),
            new Location("Portekiz", "Faro", "Faro Havalimanı (FAO)"),
            new Location("Portekiz", "Funchal", "Madeira Havalimanı (FNC)"),
            new Location("Portekiz", "Lizbon", "Lizbon Portela Havalimanı (LIS)"),
            new Location("Portekiz", "Ponta Delgada", "Ponta Delgada Havalimanı (PDL)"),
            new Location("Portekiz", "Porto", "Porto Francisco Sa Carneiro Havalimanı (OPO)"),
            new Location("Portekiz", "Porto Santo", "Porto Santo Havalimanı (PXO)"),
            new Location("Romanya", "Baia Mare", "Baia Mare Havalimanı (BAY)"),
            new Location("Romanya", "Bükreş", "Henri Coanda Uluslararası Havalimanı (OTP)"),
            new Location("Romanya", "Cluj-Napoca", "Cluj-Napoca Havalimanı (CLJ)"),
            new Location("Romanya", "Iasi", "Iasi Havalimanı (IAS)"),
            new Location("Romanya", "Köstence", "Mihail Kogalniceanu Uluslararası Havalimanı (CND)"),
            new Location("Romanya", "Oradea", "Oradea Havalimanı (OMR)"),
            new Location("Romanya", "Satu Mare", "Satu Mare Havalimanı (SUJ)"),
            new Location("Romanya", "Suceava", "Suceava Stefan cel Mare Uluslararası Havalimanı (SCV)"),
            new Location("Romanya", "Timişoara", "Timisoara Havalimanı (TSR)"),
            new Location("Rusya", "Anapa", "Anapa Havalimanı (AAQ)"),
            new Location("Rusya", "Arhangelsk", "Talagi Havalimanı (ARH)"),
            new Location("Rusya", "Belgorod", "Belgorod Uluslararası Havalimanı (EGO)"),
            new Location("Rusya", "Beslan", "Beslan Havalimanı (OGZ)"),
            new Location("Rusya", "Çelyabinsk", "Çelyabinsk Balandino Havalimanı (CEK)"),
            new Location("Rusya", "İrkutsk", "Irkutsk Havalimanı (IKT)"),
            new Location("Rusya", "Kaliningrad", "Khrabrovo Havalimanı (KGD)"),
            new Location("Rusya", "Kazan", "Kazan Uluslararası Havalimanı (KZN)"),
            new Location("Rusya", "Khanty-Mansiysk", "Khanty-Mansiysk Havalimanı (HMA)"),
            new Location("Rusya", "Krasnodar", "Pashkovsky Havalimanı (KRR)"),
            new Location("Rusya", "Krasnoyarsk", "Yemelyanovo Uluslararası Havalimanı (KJA)"),
            new Location("Rusya", "Kurgan", "Kurgan Havalimanı (KRO)"),
            new Location("Rusya", "Magnitogorsk", "Magnitogorsk Uluslararası Havalimanı (MQF)"),
            new Location("Rusya", "Mahaçkale", "Mahaçkale Uytaş Havalimanı (MCX)"),
            new Location("Rusya", "Mineralnye Vody", "Mineralnye Vody Havalimanı (MRV)"),
            new Location("Rusya", "Moskova", "Vnukovo Uluslararası Havalimanı (VKO)"),
            new Location("Rusya", "Moskova", "Domodedovo Uluslararası Havalimanı (DME)"),
            new Location("Rusya", "Murmansk", "Murmansk Havalimanı (MMK)"),
            new Location("Rusya", "Nijnevartovsk", "Nijnevartovsk Havalimanı (NJC)"),
            new Location("Rusya", "Nizhny Novgorod", "Strigino Uluslararası Havalimanı (GOJ)"),
            new Location("Rusya", "Novosibirsk", "Novosibirsk Tolmachevo Havalimanı (OVB)"),
            new Location("Rusya", "Omsk", "Tsentralny Havalimanı (OMS)"),
            new Location("Rusya", "Perm", "Perm Bolshoye Savino Havalimanı (PEE)"),
            new Location("Rusya", "Rostov-na-Donu", "Rostov-na-Donu Uluslararası Havalimanı (ROV)"),
            new Location("Rusya", "Samara", "Samara Havalimanı (KUF)"),
            new Location("Rusya", "Sıktıvkar", "Syktyvkar Havalimanı (SCW)"),
            new Location("Rusya", "Soçi", "Adler-Sochi Uluslararası Havalimanı (AER)"),
            new Location("Rusya", "St. Petersburg", "St Petersburg Pulkovo Havalimanı (LED)"),
            new Location("Rusya", "Surgut", "Surgut Uluslararası Havalimanı (SGC)"),
            new Location("Rusya", "Şupaşkar", "Şupaşkar Uluslararası Havalimanı (CSY)"),
            new Location("Rusya", "Tomsk", "Tomsk Bogaşevo Havalimanı (TOF)"),
            new Location("Rusya", "Tümen", "Roşçino Uluslararası Havalimanı (TJM)"),
            new Location("Rusya", "Ufa", "Ufa Uluslararası Havalimanı (UFA)"),
            new Location("Rusya", "Ulyanovsk", "Vostoşni Havalimanı (ULY)"),
            new Location("Rusya", "Usinsk", "Usinsk Havalimanı (USK)"),
            new Location("Rusya", "Volgograd", "Volgograd Uluslararası Havalimanı (VOG)"),
            new Location("Rusya", "Voronej", "Chertovitskoye Havalimanı (VOZ)"),
            new Location("Rusya", "Yarçallı", "Begişevo Havalimanı (NBC)"),
            new Location("Rusya", "Yekaterinburg", "Yekaterinburg Koltsovo Havalimanı (SVX)"),
            new Location("Rusya", "Yoşkar-Ola", "Yoşkar Ola Havalimanı (JOK)"),
            new Location("Türkiye", "Adana", "Adana Havalimanı (ADA)"),
            new Location("Türkiye", "Adana", "Çukurova Havalimanı (COV)"),
            new Location("Türkiye", "Adıyaman", "Adıyaman Havalimanı (ADF)"),
            new Location("Türkiye", "Ağrı", "Ağrı Havalimanı (AJI)"),
            new Location("Türkiye", "Alanya", "Gazipaşa Alanya Havalimanı (GZP)"),
            new Location("Türkiye", "Amasya", "Amasya Merzifon Havalimanı (MZH)"),
            new Location("Türkiye", "Ankara", "Ankara Esenboğa Havalimanı (ESB)"),
            new Location("Türkiye", "Antalya", "Antalya Havalimanı (AYT)"),
            new Location("Türkiye", "Balıkesir - Edremit", "Koca Seyit Havalimanı (EDO)"),
            new Location("Türkiye", "Batman", "Batman Havalimanı (BAL)"),
            new Location("Türkiye", "Bingöl", "Bingöl Havalimanı (BGG)"),
            new Location("Türkiye", "Bursa", "Bursa Yenişehir Havalimanı (YEI)"),
            new Location("Türkiye", "Çanakkale", "Çanakkale Havalimanı (CKZ)"),
            new Location("Türkiye", "Denizli", "Denizli Çardak Havalimanı (DNZ)"),
            new Location("Türkiye", "Diyarbakır", "Diyarbakır Havalimanı (DIY)"),
            new Location("Türkiye", "Elazığ", "Elazığ Havalimanı (EZS)"),
            new Location("Türkiye", "Erzincan", "Erzincan Yıldırım Akbulut Havalimanı (ERC)"),
            new Location("Türkiye", "Erzurum", "Erzurum Havalimanı (ERZ)"),
            new Location("Türkiye", "Eskişehir", "Hasan Polatkan Havalimanı (AOE)"),
            new Location("Türkiye", "Gaziantep", "Gaziantep Havalimanı (GZT)"),
            new Location("Türkiye", "Hakkari", "Yüksekova Havalimanı (YKO)"),
            new Location("Türkiye", "Hatay", "Hatay Havalimanı (HTY)"),
            new Location("Türkiye", "Iğdır", "Iğdır Şehit Bülent Aydın Havalimanı (IGD)"),
            new Location("Türkiye", "Isparta", "Isparta Süleyman Demirel Havalimanı (ISE)"),
            new Location("Türkiye", "İstanbul", "İstanbul Havalimanı (IST)"),
            new Location("Türkiye", "İstanbul", "Sabiha Gökçen Havalimanı (SAW)"),
            new Location("Türkiye", "İzmir", "İzmir Adnan Menderes Havalimanı (ADB)"),
            new Location("Türkiye", "Kahramanmaraş", "Kahramanmaraş Havalimanı (KCM)"),
            new Location("Türkiye", "Kars", "Kars Harakani Havalimanı (KSY)"),
            new Location("Türkiye", "Kastamonu", "Kastamonu Havalimanı (KFS)"),
            new Location("Türkiye", "Kayseri", "Kayseri Havalimanı (ASR)"),
            new Location("Türkiye", "Kocaeli", "Kocaeli Cengiz Topel Havalimanı (KCO)"),
            new Location("Türkiye", "Konya", "Konya Havalimanı (KYA)"),
            new Location("Türkiye", "Kütahya", "Zafer Bölgesel Havalimanı (KZR)"),
            new Location("Türkiye", "Malatya", "Malatya Havalimanı (MLX)"),
            new Location("Türkiye", "Mardin", "Mardin Prof. Dr. Aziz Sancar Havalimanı (MQM)"),
            new Location("Türkiye", "Muğla-Bodrum", "Milas-Bodrum Havalimanı (BJV)"),
            new Location("Türkiye", "Muğla-Dalaman", "Dalaman Havalimanı (DLM)"),
            new Location("Türkiye", "Muş", "Muş Havalimanı (MSR)"),
            new Location("Türkiye", "Nevşehir", "Nevşehir Kapadokya Havalimanı (NAV)"),
            new Location("Türkiye", "Ordu-Giresun", "Ordu-Giresun Havalimanı (OGU)"),
            new Location("Türkiye", "Rize", "Rize Artvin Havalimanı (RZV)"),
            new Location("Türkiye", "Samsun", "Samsun Çarşamba Havalimanı (SZF)"),
            new Location("Türkiye", "Siirt", "Siirt Havalimanı (SXZ)"),
            new Location("Türkiye", "Sinop", "Sinop Havalimanı (NOP)"),
            new Location("Türkiye", "Sivas", "Sivas Nuri Demirağ Havalimanı (VAS)"),
            new Location("Türkiye", "Şanlıurfa", "Şanlıurfa GAP Havalimanı (GNY)"),
            new Location("Türkiye", "Şırnak", "Şırnak Şerafettin Elçi Havalimanı (NKT)"),
            new Location("Türkiye", "Tokat", "Tokat Havalimanı (TJK)"),
            new Location("Türkiye", "Trabzon", "Trabzon Havalimanı (TZX)"),
            new Location("Türkiye", "Uşak", "Uşak Havalimanı (USQ)"),
            new Location("Türkiye", "Van", "Van Ferit Melen Havalimanı (VAN)"),
            new Location("Türkiye", "Zonguldak", "Zonguldak Havalimanı (ONQ)"),
            new Location("Türkmenistan", "Aşkabat", "Aşkabat Uluslararası Havalimanı (ASB)"),
            new Location("Türkmenistan", "Türkmenabat", "Türkmenabat Uluslararası Havalimanı (CRZ)"),
            new Location("Türkmenistan", "Türkmenbaşı", "Türkmenbaşı Uluslararası Havalimanı (KRW)"),
            new Location("Ukrayna", "Harkiv", "Harkiv Uluslararası Havalimanı (HRK)"),
            new Location("Ukrayna", "Herson", "Herson Havalimanı (KHE)"),
            new Location("Ukrayna", "Kiev", "Kiev Borispol Havalimanı (KBP)"),
            new Location("Ukrayna", "Kiev", "Kiev Zhuliany Uluslararası Havalimanı (IEV)"),
            new Location("Ukrayna", "Lviv", "Lviv Danylo Halytskyi Uluslararası Havalimanı (LWO)"),
            new Location("Ukrayna", "Mykolaiv", "Mykolaiv Uluslararası Havalimanı (NLV)"),
            new Location("Ukrayna", "Odessa", "Odessa Uluslararası Havalimanı (ODS)"),
            new Location("Ukrayna", "Zaporijya", "Zaporijya Uluslararası Havalimanı (OZH)"),
            new Location("Yunanistan", "Aleksandropolis", "Aleksandropolis Havalimanı (AXD)"),
            new Location("Yunanistan", "Atina", "Atina Elefterios Venizelos Uluslararası Havalimanı (ATH)"),
            new Location("Yunanistan", "Chios Island", "Chios Havalimanı (JKH)"),
            new Location("Yunanistan", "Crete Island", "Sitia Havalimanı (JSH)"),
            new Location("Yunanistan", "Ikaria Island", "Ikaria Island Havalimanı (JIK)"),
            new Location("Yunanistan", "Kalamata", "Kalamata Havalimanı (KLX)"),
            new Location("Yunanistan", "Kandiye", "Nikos Kazancakis Havalimanı (HER)"),
            new Location("Yunanistan", "Kastelorizo Island", "Kastelorizo Havalimanı (KZS)"),
            new Location("Yunanistan", "Kavala", "Kavala Havalimanı (KVA)"),
            new Location("Yunanistan", "Kefalonya", "Kefalonya Havalimanı (EFL)"),
            new Location("Yunanistan", "Kerpe Adası", "Karpathos Havalimanı (AOK)"),
            new Location("Yunanistan", "Kithira Island", "Kithira Havalimanı (KIT)"),
            new Location("Yunanistan", "Korfu", "Kerkyra Havalimanı (CFU)"),
            new Location("Yunanistan", "Kos", "Kos Havalimanı (KGS)"),
            new Location("Yunanistan", "Lemnos", "Limnos Havalimanı (LXS)"),
            new Location("Yunanistan", "Leros Island", "Leros Havalimanı (LRS)"),
            new Location("Yunanistan", "Midilli", "Midilli Havalimanı (MJT)"),
            new Location("Yunanistan", "Mikonos", "Mikonos Havalimanı (JMK)"),
            new Location("Yunanistan", "Milos Island", "Milos Havalimanı (MLO)"),
            new Location("Yunanistan", "Naxos Island", "Naxos Is Havalimanı (JNX)"),
            new Location("Yunanistan", "Paros Island", "Paros Havalimanı (PAS)"),
            new Location("Yunanistan", "Preveze/Lefkada", "Preveze/Lefkada Havalimanı (PVK)"),
            new Location("Yunanistan", "Rodos", "Rodos Havalimanı (RHO)"),
            new Location("Yunanistan", "Samos Island", "Samos Havalimanı (SMI)"),
            new Location("Yunanistan", "Santorini Island", "Santorini Havalimanı (JTR)"),
            new Location("Yunanistan", "Selanik", "Selanik Macedonia Havalimanı (SKG)"),
            new Location("Yunanistan", "Skiathos", "Skiathos Havalimanı (JSI)"),
            new Location("Yunanistan", "Skiros Island", "Skiros Havalimanı (SKU)"),
            new Location("Yunanistan", "Souda", "Ioannis Daskalogiannis Havalimanı (CHQ)"),
            new Location("Yunanistan", "Yanya", "Yanya Havalimanı (IOA)"),
            new Location("Yunanistan", "Zakinthos Island", "Zakinthos Island Havalimanı (ZTH)")
        };

        public static void fillCountries()
        {
            var countries = locations.Select(obj => obj.Country).Distinct().ToList();
            MainForm.comboCountry.DataSource = countries;
        }

        public static void fillCities(string selectedCountry)
        {
            var cities = locations.Where(obj => obj.Country == selectedCountry).Select(obj => obj.City).Distinct().ToList();
            MainForm.comboCity.DataSource = cities;
        }

        public static void fillAirports(string selectedCountry, string selectedCity)
        {
            var airports = locations.Where(obj => obj.Country == selectedCountry && obj.City == selectedCity).Select(obj => obj.Airport).Distinct().ToList();
            MainForm.comboAirport.DataSource = airports;
        }
    }
}
